version: "2"
services:

 festival-db:
    image: gcr.io/fluid-axe-202119/festival-db:dev
    command: postgres -c wal_level=logical -c max_wal_senders=10 -c max_replication_slots=10 -c log_error_verbosity=TERSE
    ports:
     - ${DB_PORT}:5432
    volumes:
     - ./dump:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}

 festival-app:
   image: node:8.9
   depends_on:
    - festival-db
   links:
    - festival-db
   ports:
    - 8090:8090
   working_dir: /usr/local/src/festivalapp
   volumes:
    - ./:/usr/local/src/festivalapp
   command: ["./tools/wait-for-it.sh", "festival-db:5432", "--", "./tools/start.sh"]
   environment:
     APP_PORT: ${APP_PORT}
     NODE_ENV: ${NODE_ENV}
     DB_PORT: ${DB_PORT}
     DB_HOST: ${DB_HOST}
     DB_USER: ${DB_USER}
     DB_PASSWORD: ${DB_PASSWORD}
     DB_DATABASE: ${DB_DATABASE}

volumes:
  data: {}
